# Generated by Django 4.2.7 on 2023-12-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='direccion_ip',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='IPv4'),
        ),
    ]
