# Generated by Django 4.2.7 on 2023-12-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_location_direccion_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
