# Generated by Django 4.2.7 on 2023-12-01 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_ubicacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ubicacion',
            new_name='UbicacionInicial',
        ),
    ]
