# Generated by Django 4.2.7 on 2023-12-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_rename_ubicacion_ubicacioninicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='ping_responde',
            field=models.BooleanField(default=0),
        ),
    ]
