# Generated by Django 4.2.7 on 2023-12-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_location_ping_responde'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoJSONFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='geojson_files/', verbose_name='Archivo GeoJSON')),
                ('color', models.CharField(default='black', max_length=30, verbose_name='Color de líneas')),
                ('weight', models.IntegerField(default=2, verbose_name='Grosor de líneas')),
                ('opacity', models.FloatField(default=0.4, verbose_name='Opacidad de líneas')),
                ('fillColor', models.CharField(default='red', max_length=30, verbose_name='Color de relleno')),
                ('fillOpacity', models.FloatField(default=0.1, verbose_name='Opacidad de relleno')),
            ],
            options={
                'verbose_name': 'Archivo GeoJSON',
                'verbose_name_plural': 'Archivos GeoJSON',
            },
        ),
    ]
